### ISSUE TITLE
Does not support intersection with vertical line?

### ISSUE THREAD

**Issue by poonwu** [tmpvar/line2#4]
`line2.intersect` throw error when the slope is `Infinity`

**Comment by W1U02** [comment]
can add the following code to [line 303](https://github.com/tmpvar/line2/blob/master/line2.js#L303) to fix this issue
```js
    if (!finite(s1) && !finite(s2)) {
        return (this.yintercept() === line.yintercept() &&
            this.xintercept() === line.xintercept());
    }
```

**Comment by tmpvar** [comment]
Can you send me a pull request with a test that exercises this behavior? Thanks!
